spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://mysql.coffit.today/oneinfurniture
    username: oneinfurniture
    password: oneinfurniture1234


    spring:
      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB
          location: C:/images/

image:
  image-dir: img

mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.hedgehog
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info