spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<<<< Temporary merge branch 1
    url: jdbc:mysql://mysql.coffit.today:3306/oneinfurniture
    username: oneinfurniture
    password: oneinfurniture1234
=========
    url: jdbc:mysql://mysql.coffit.today/oneinfurniture
    username: oneinfurniture
    password: oneinfurniture1234

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.hedgehog
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
>>>>>>>>> Temporary merge branch 2
