spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.coffit.today:3306/oneinfurniture
    username: oneinfurniture
    password: oneinfurniture1234


    spring:
      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB
          location: C:/images/

    image:
      image-dir: img

    mybatis:
      # mapper.xml location Setting
      mapper-locations: mybatis/mapper/*.xml
      # alias Setting
      type-aliases-package: com.hedgehog
      configuration:
        map-underscore-to-camel-case: true

    logging:
      level:
        root: info