

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.coffit.today/oneinfurniture
    username: oneinfurniture
    password: oneinfurniture1234

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/images/

  image:
    image-dir: ima

  mybatis:
    # mapper.xml 위치 설정
    mapper-locations: mybatis/mapper/*.xml
    # 별칭 설정
    type-aliases-package: com.hedgehog
    configuration:
      map-underscore-to-camel-case: true

  logging:
    level:
      root: info